site:
  title: "Wallace Santana - Timeline"
  description: "Bem vindo(a) minha timeline pessoal"
personal:
  name: "Wallace Santana"
  avatar: "https://github.com/wallacemt.png"
  socialNetworks:
    youtube: "https://www.youtube.com/wallacemt"
    github: "https://www.github.com/wallacemt"
    linkedin: "https://www.linkedin.com/in/wallace-santanak0"
